$Name,

It is that time of year again where we reach out to a handful of awesome individuals and invite them to take an active role in the DEF CON Hardware Hacking Village.

We love the work you do and would be grateful to have you bring something to share. Anything that takes the hardware shenanigans to the max. It could be a hands-on demonstration of a technique, or process, a short workshop, or just time to sit and chat with community members about a cool project you have or are working on. This year even moreso than others we are looking for activities that engage those in attendance; something you can't get from a good video.

If you are interested, our CFP is live now: $CFP_link

Also, this year we will be running a "Make Your Own Use" contest! We are looking for judges, would you be interested in volunteering to be a judge? The concept of the contest is submissions can be made based on any project that worked on over the year, there may be 3 categories for a) repairing a closed device, b) adding a feature to a device that was never intended, c) bypassing DRM on devices to unlock their full potential -- if there are many submissions. We expect the judges to award points based on 1) how bent/changed/diferent/unintended it is 2) re-work quality 3) re-work ingenuity 4) weirdness (it is DEF CON).

If you are interested in being a judge, please let us know.

If you are not interested or able this year, I hope we can make something work in the future. If you would like to never hear from us again, just let me know and I'll make sure that we never send you a request in the future.

Happy Hacking!

--

DEF CON Hardware Hacking Village
