$Name,

It is that time of year again where we reach out to a handful of awesome individuals and invite them to give a presentation in the DEF CON Hardware Hacking Village.

We love the work you do and would be grateful to have you give a hands-on demonstration or short workshop for our attendees. Anything that takes the hardware shenanigans to the max.

If you are interested, our CFP is live now: $CFP_link

If you are not interested or able this year, I hope we can make something work in the future. If you would like to never hear from us again, just let me know and I'll make sure that we never send you a request in the future.

Happy Hacking!

--

l33tbunni
DEF CON Hardware Hacking Village
