$Name,

It is that time of year again where we reach out to a handful of awesome individuals and invite them to take an active role in the DEF CON Hardware Hacking Village.

We love the work you do and would be grateful to have you bring something to share. Anything that takes the hardware shenanigans to the max. It could be a hands-on demonstration of a technique, or process, a short workshop, or just time to sit and chat with community members about a cool project you have or are working on. This year even moreso than others we are looking for activities that engage those in attendance; something you can't get from a good video.

If you are interested, our CFP is live now: $CFP_link

Also, this year a number of contests need judges -- like the Make Your Own Use and Rube Goldberg machine contests. Rather than set up an arbitrary panel, we want to encourage any that want to participate to sign up to be a judge. We will have specific details of events coming out over the next few months. As we assign judges to specific events we will work with you on expectations and time requirements.

If you are interested in being a judge, please let us know.

If you are not interested or able this year, I hope we can make something work in the future. If you would like to never hear from us again, just let me know and I'll make sure that we never send you a request in the future.

Happy Hacking!

--

DEF CON Hardware Hacking Village
