$Name,

Thank you so much for helping us make this a great year!

If you would be so willing, we would love to gather feedback on what you thought of our space and our team. No rush, but we wanted to get this out before details started to slip away.

Space:
- What did you like about the talk space?
- What didn't you like about the talk space?
- What suggestions do you have for us about future talk/workshop spaces?

Planning and staff:
- Do you have any feedback on our CFP process, the information we provided up to DEF CON, or how we advertised it?
- Were there any notable HHV/SSV staff?

Misc:
- Would you be interested in speaking again in the future as a continuation of your topic this year or on a different topic?

Thank you again for your time!

Happy Hacking!

--

$Signature
DEF CON Hardware Hacking Village
