$Name,

Thank you for proposing to give the presentation:
"$Title"

However, we regret to inform you that it was not selected as a presentation for the DEF CON $DC_num Hardware Hacking Village. We thank you for your submission and hope you can still join us this year for awesome hardware shenanigans.

You are encouraged to refine your CFP submission and submit it to other conferences or again next year. If you would like some feedback on your submission, please let me know and I can pass along comments of our selection team.

Happy Hacking!
