$Name,

Good news! We have been informed that we're getting human badges to give to our presenters!

These will be managed by DEF CON Creator Stages and you will need to pick them up from the Creator Stage Ready Room (or In-Human Registration, see below). In order to do so you will need to provide, for each presenter, either:

- BOTH your legal name that appears on a government issued ID -AND- show this ID to DEF CON staff for badge pickup 

-OR-

- Provide me a passphrase that you can repeat at badge pickup in order to receive your badge


You can pick up your Human badge on Thursday from $Badge_meet; or on Friday or Saturday from In-Human Registration. In either case, a government issued ID or passphrase will be required for this as noted above!

Note that if you have multiple presenters, each presenter will need to pick up their own badge!

If you are receiving a Human badge from another department (like Contests, Villages, etc.) you will not be given a second badge from the Creator Stages.

Presenters are asked to arrive to Speaker Ops ($Speaker_ops) at least 45 minutes before their scheduled time.

All talks will be recorded and uploaded to the DEF CON media server.

Happy Hacking!

--

$Signature
DEF CON Hardware Hacking Village
