$Name,

Thank you for proposing to give the presentation:
"$Title"

It has been accepted as a presentation for the DEF CON $DC_num Hardware Hacking Village

$Additional_Comments

What you need to do right now:

1) Reply to this email to confirm that you will be able to give this presentation during DEF CON $DC_num, $DC_days. You will have until $Response_deadline to confirm this. If we do not hear from you by then, we will regrettably need to rescind this offer.

2) Send me any desired edits for your talk title, description, and bio, which we'll be listing on the website exactly as they appear below:

"$Title"

"$Abstract"

"$Bio"


You have until $Response_deadline to change this if needed!


3) Wait until we post the schedule before you announce that you're speaking, as not every proposal submitter has heard back yet. We intend on posting the schedule to the dchhv.org site in the near future. We will tweet about it from @DC_HHV (Twitter/Xitter/Whatever) and @DC_HHV@defcon.social when it's up and ready.


What you should do before archiving this email:

1) Let me know if you would like to do a call to discuss your talk. I'm happy to give feedback/input/ideas. No need to have any slides ready for this and there is no obligation to do this if you are comfortable with your talk.


What you will want to know eventually:

1) We try to provide human badges to HHV presenters. Note that we are at the mercy of DEF CON to be able to provide these. If we are able to provide a human badge we will let you know in a separate email. If you have any questions or concerns please let me know ASAP.

2) While we will release the schedule online, we will also send an email detailing your talk slot with further information.

3) If you want your slide deck and/or other media related to your presentation available on the DEF CON media server, please provide everything before $Content_deadline.


If you have any questions, comments, or concerns, please let me know as soon as possible!

Happy Hacking!

--

$Signature
DEF CON Hardware Hacking Village
