$Name,

Please provide your presentations, and any additional media that is a part of it, to me by $Content_deadline in order for them to be uploaded to the DEF CON media servers to be available for the duration of the conference.

PDF is preferred for presentation materials such as a slide deck, photos, etc. Please name them in the format "DEF CON 33 - HHV & SSV - <Presenter> [& <Co-presenter] - <Presentation Title>.pdf"

Videos can be in any common format, but please name them using the same format.

If media files are too large to attach to an email, please provide a link to a location that they can be accessed by DEF CON staff for re-uploading to the DEF CON media servers.


Happy Hacking!

--

$Signature
DEF CON Hardware Hacking Village
