$Name,

Good news! We have been informed that we're getting human badges to give to our presenters!

Below is a short string, this is your unique identifier, do not share it with anyone else or you won't get your badge! Bring this to the meeting location (just jot it on a piece of paper) noted below to receive your human badge and all of the other reg goodies that come along with it. If you are unable to meet me at the time noted below then please let me know ASAP.  If you do not want the human badge for any reason, let me know and we will ensure it gets to a good home.

$Badge_meet
Your unique ID: "$Badge_uniqID"
You can't miss me, I will have on a decently sized green knit hat in the shape of a dragon. If you have any issues at con, don't forget you can reach me at $Organizer_phone.

Happy Hacking!

--

l33tbunni
DEF CON Hardware Hacking Village
