$Name,

Your presentation:
"$Title"

Is currently scheduled on:
$Time

What you need to do right now:

1) Confirm that this time slot works for you. If this time does not work for you for any reason, please let us know by $Schedule_deadline.  After which time we cannot change the schedule as it needs to be submitted to DEF CON.

What you need to know moving forward:

1) Please familiarize yourself with the DEF CON conference layout and the location of the HHV; you can find the floormap here: $DC_floormapurl

2) Even if you indicated that you would like your presentation to be recorded, we unfortunately cannot guarantee a recording at this time.  This is still being worked out on the DEF CON logistics side.

3) We will have available a projector, podium with power, speakers, and microphone setup.  Historically we have had a lapel mic as well as a standing mic; one or both of these will likely be available. The projector will likely have an HDMI input, however we cannot guarantee any specific input types. Therefore we recommend bringing any adaptors you may need for various video output types. We cannot guarantee the ability to connect directly to the audio system either, but you can always ask on-site.

4) We will not ask for presentation slides ahead of time nor do we have a template or any guidelines. Take your time and style it how you like. We will gladly provide feedback if you ask.

5) It is alright if your presentation is shorter than your projected time, however it is up to you to end no later than that time as we will have a full schedule.  We will do our best to keep you on schedule but we do not have enough volunteers to put someone on proctor duty.

6) Please show up to the HHV operations table and check in with "$Organizer" no less than 10 minutes before your talk is scheduled to begin.  We won't turn you away for being late, but the waiting crowd might get angry.

7) I will not be readily available via email during DEF CON.  If you have any questions or concerns on or after $Radiosilent_deadline, please locate "$Organizer" in the HHV ops area.

If you have any comments or questions, please let me know and we will get back to you as soon as we can!

Happy Hacking!

--

$Signature
DEF CON Hardware Hacking Village
